
services:
  web:
    build: .  # Construye la imagen desde el Dockerfile en el directorio actual
    image: api_automation_itop
    command: ["gunicorn", "api_automatizacion.wsgi:application", "--bind", "0.0.0.0:8000"]  # Comando para ejecutar el servidor Gunicorn
    volumes:
      - .:/app  # Monta el directorio actual en el contenedor en /app
    ports:
      - "8000:8000"  # Expone el puerto 8000 del contenedor en el puerto 8000 del host
    env_file:
      - .env  # Carga las variables de entorno desde el archivo .env
    depends_on:
      - db  # Asegura que el servicio db esté en marcha antes de iniciar este servicio

  scheduler: 
    image: api_automation_itop 
    command: ["python", "manage.py", "create_schedule"]
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8.0  # Usa la imagen oficial de MySQL versión 8.0
    environment:
      MYSQL_DATABASE: api_rest 
      MYSQL_USER: db_user_api  
      MYSQL_PASSWORD: S2UjmhNDxZhu9ZSar228urD  
      MYSQL_ROOT_PASSWORD: A4SQL3qUPPS3z77ij7fjlñ  
    ports:
      - "3307:3306"  
volumes:
  db_data: 
