# Generated by Django 4.2 on 2024-10-03 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthBlocked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuthGenerated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialPComputer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('organization_id', models.CharField(blank=True, max_length=30, null=True)),
                ('location_id', models.CharField(blank=True, max_length=30, null=True)),
                ('brand_id', models.CharField(blank=True, max_length=30, null=True)),
                ('model_id', models.CharField(blank=True, max_length=30, null=True)),
                ('osfamily_id', models.CharField(blank=True, max_length=30, null=True)),
                ('type', models.CharField(blank=True, max_length=30, null=True)),
                ('cpu', models.CharField(blank=True, max_length=50, null=True)),
                ('os_version_id', models.CharField(blank=True, max_length=30, null=True)),
                ('serialnumber', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(blank=True, max_length=15, null=True)),
                ('ram', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=600, null=True)),
                ('move2production', models.DateField(blank=True, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('end_of_warranty', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PComputer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('organization_id', models.CharField(blank=True, max_length=30, null=True)),
                ('location_id', models.CharField(blank=True, max_length=30, null=True)),
                ('brand_id', models.CharField(blank=True, max_length=30, null=True)),
                ('model_id', models.CharField(blank=True, max_length=30, null=True)),
                ('osfamily_id', models.CharField(blank=True, max_length=30, null=True)),
                ('type', models.CharField(blank=True, max_length=30, null=True)),
                ('cpu', models.CharField(blank=True, max_length=50, null=True)),
                ('os_version_id', models.CharField(blank=True, max_length=30, null=True)),
                ('serialnumber', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(blank=True, max_length=15, null=True)),
                ('ram', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=600, null=True)),
                ('move2production', models.DateField(blank=True, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('end_of_warranty', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SerialAndService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('service_id', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
