# Generated by Django 5.1.1 on 2024-09-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('organization_name', models.CharField(blank=True, max_length=60, null=True)),
                ('location_name', models.CharField(blank=True, max_length=60, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=40, null=True)),
                ('model_name', models.CharField(blank=True, max_length=40, null=True)),
                ('osfamily_name', models.CharField(blank=True, max_length=40, null=True)),
                ('type', models.CharField(blank=True, max_length=40, null=True)),
                ('cpu', models.CharField(blank=True, max_length=40, null=True)),
                ('os_version_name', models.CharField(blank=True, max_length=40, null=True)),
                ('serialnumber', models.CharField(default='', max_length=40, unique=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('ram', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('move2production', models.DateField(blank=True, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('end_of_warranty', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialComputer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('organization_name', models.CharField(blank=True, max_length=50, null=True)),
                ('location_name', models.CharField(blank=True, max_length=50, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=30, null=True)),
                ('model_name', models.CharField(blank=True, max_length=30, null=True)),
                ('osfamily_name', models.CharField(blank=True, max_length=30, null=True)),
                ('type', models.CharField(blank=True, max_length=30, null=True)),
                ('cpu', models.CharField(blank=True, max_length=50, null=True)),
                ('os_version_name', models.CharField(blank=True, max_length=50, null=True)),
                ('serialnumber', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(blank=True, max_length=15, null=True)),
                ('ram', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=600, null=True)),
                ('move2production', models.DateField(blank=True, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('end_of_warranty', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SerialAndIDItop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('id_itop', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TokenGenerated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
