# Generated by Django 5.1.1 on 2024-09-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialcomputer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='historialcomputer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
