# Generated by Django 4.2 on 2024-10-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('organization_id', models.CharField(blank=True, max_length=30, null=True)),
                ('location_id', models.CharField(blank=True, max_length=30, null=True)),
                ('brand_id', models.CharField(blank=True, max_length=30, null=True)),
                ('model_id', models.CharField(blank=True, max_length=30, null=True)),
                ('osfamily_id', models.CharField(blank=True, max_length=30, null=True)),
                ('type', models.CharField(blank=True, max_length=30, null=True)),
                ('cpu', models.CharField(blank=True, max_length=50, null=True)),
                ('os_version_id', models.CharField(blank=True, max_length=30, null=True)),
                ('serialnumber', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(blank=True, max_length=15, null=True)),
                ('ram', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=600, null=True)),
                ('move2production', models.DateField(blank=True, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('end_of_warranty', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
